-- MySQL Script generated by MySQL Workbench
-- Sat May  5 02:35:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db` ;

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`real_estate_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`real_estate_company` ;

CREATE TABLE IF NOT EXISTS `db`.`real_estate_company` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `phone_number` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `company_name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`user` ;

CREATE TABLE IF NOT EXISTS `db`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `password_salt` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `is_active` TINYINT(1) NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL,
  `phone_number` VARCHAR(255) NULL,
  `real_estate_company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `password_salt_UNIQUE` (`password_salt` ASC),
  INDEX `fk_user_real_estate_company1_idx` (`real_estate_company_id` ASC),
  CONSTRAINT `fk_user_real_estate_company1`
    FOREIGN KEY (`real_estate_company_id`)
    REFERENCES `db`.`real_estate_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`country` ;

CREATE TABLE IF NOT EXISTS `db`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `coutry_abbrev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`city` ;

CREATE TABLE IF NOT EXISTS `db`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `db`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`district`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`district` ;

CREATE TABLE IF NOT EXISTS `db`.`district` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_district_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_district_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `db`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`microdistrict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`microdistrict` ;

CREATE TABLE IF NOT EXISTS `db`.`microdistrict` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `district_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_microdistrict_district1_idx` (`district_id` ASC),
  CONSTRAINT `fk_microdistrict_district1`
    FOREIGN KEY (`district_id`)
    REFERENCES `db`.`district` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`real_estate_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`real_estate_address` ;

CREATE TABLE IF NOT EXISTS `db`.`real_estate_address` (
  `id` INT NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `microdistrict_id` INT NOT NULL,
  `district_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_real_estate_address_microdistrict1_idx` (`microdistrict_id` ASC),
  INDEX `fk_real_estate_address_district1_idx` (`district_id` ASC),
  INDEX `fk_real_estate_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_real_estate_address_microdistrict1`
    FOREIGN KEY (`microdistrict_id`)
    REFERENCES `db`.`microdistrict` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_real_estate_address_district1`
    FOREIGN KEY (`district_id`)
    REFERENCES `db`.`district` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_real_estate_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `db`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`user_real_estate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`user_real_estate` ;

CREATE TABLE IF NOT EXISTS `db`.`user_real_estate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT NULL,
  `house_material` VARCHAR(255) NULL,
  `rooms_count` INT NULL,
  `living_space` DOUBLE NULL,
  `total_space` DOUBLE NULL,
  `floor` INT NULL,
  `building_year` INT NULL,
  `is_rent` TINYINT(1) NULL,
  `is_active` TINYINT(1) NULL DEFAULT 1,
  `user_id` INT UNSIGNED NOT NULL,
  `real_estate_address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_real_estate_user_idx` (`user_id` ASC),
  INDEX `fk_user_real_estate_real_estate_address1_idx` (`real_estate_address_id` ASC),
  CONSTRAINT `fk_user_real_estate_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_real_estate_real_estate_address1`
    FOREIGN KEY (`real_estate_address_id`)
    REFERENCES `db`.`real_estate_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `db`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `user_real_estate_id` INT NOT NULL,
  INDEX `fk_timestamps_user_real_estate1_idx` (`user_real_estate_id` ASC),
  CONSTRAINT `fk_timestamps_user_real_estate1`
    FOREIGN KEY (`user_real_estate_id`)
    REFERENCES `db`.`user_real_estate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`chat` ;

CREATE TABLE IF NOT EXISTS `db`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`user_chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`user_chats` ;

CREATE TABLE IF NOT EXISTS `db`.`user_chats` (
  `chat_id` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `is_readed` TINYINT(1) NULL,
  PRIMARY KEY (`chat_id`, `user_id`),
  INDEX `fk_chat_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_chat_has_user_chat1_idx` (`chat_id` ASC),
  CONSTRAINT `fk_chat_has_user_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `db`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`message` ;

CREATE TABLE IF NOT EXISTS `db`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  `chat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_message_chat1_idx` (`chat_id` ASC),
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `db`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`role` ;

CREATE TABLE IF NOT EXISTS `db`.`role` (
  `id` INT NOT NULL,
  `role_name` VARCHAR(255) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC),
  INDEX `fk_role_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`company_complex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`company_complex` ;

CREATE TABLE IF NOT EXISTS `db`.`company_complex` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `complex_year` INT NULL,
  `real_estate_company_id` INT NOT NULL,
  `real_estate_address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_complex_real_estate_company1_idx` (`real_estate_company_id` ASC),
  INDEX `fk_company_complex_real_estate_address1_idx` (`real_estate_address_id` ASC),
  CONSTRAINT `fk_company_complex_real_estate_company1`
    FOREIGN KEY (`real_estate_company_id`)
    REFERENCES `db`.`real_estate_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_complex_real_estate_address1`
    FOREIGN KEY (`real_estate_address_id`)
    REFERENCES `db`.`real_estate_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`statistics` ;

CREATE TABLE IF NOT EXISTS `db`.`statistics` (
  `id` INT NOT NULL,
  `crime_stat` DOUBLE NOT NULL,
  `transport_stat` DOUBLE NOT NULL,
  `price_stat` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`district_has_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`district_has_statistics` ;

CREATE TABLE IF NOT EXISTS `db`.`district_has_statistics` (
  `district_id` INT NOT NULL,
  `statistics_id` INT NOT NULL,
  PRIMARY KEY (`district_id`, `statistics_id`),
  INDEX `fk_district_has_statistics_statistics1_idx` (`statistics_id` ASC),
  INDEX `fk_district_has_statistics_district1_idx` (`district_id` ASC),
  CONSTRAINT `fk_district_has_statistics_district1`
    FOREIGN KEY (`district_id`)
    REFERENCES `db`.`district` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_district_has_statistics_statistics1`
    FOREIGN KEY (`statistics_id`)
    REFERENCES `db`.`statistics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`microdistrict_has_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`microdistrict_has_statistics` ;

CREATE TABLE IF NOT EXISTS `db`.`microdistrict_has_statistics` (
  `microdistrict_id` INT NOT NULL,
  `statistics_id` INT NOT NULL,
  PRIMARY KEY (`microdistrict_id`, `statistics_id`),
  INDEX `fk_microdistrict_has_statistics_statistics1_idx` (`statistics_id` ASC),
  INDEX `fk_microdistrict_has_statistics_microdistrict1_idx` (`microdistrict_id` ASC),
  CONSTRAINT `fk_microdistrict_has_statistics_microdistrict1`
    FOREIGN KEY (`microdistrict_id`)
    REFERENCES `db`.`microdistrict` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_microdistrict_has_statistics_statistics1`
    FOREIGN KEY (`statistics_id`)
    REFERENCES `db`.`statistics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`user_find_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`user_find_place` ;

CREATE TABLE IF NOT EXISTS `db`.`user_find_place` (
  `id` INT NOT NULL,
  `first_longitude` DOUBLE NOT NULL,
  `first_latitude` DOUBLE NOT NULL,
  `second_longitude` DOUBLE NOT NULL,
  `second_latitude` DOUBLE NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_find_place_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_find_place_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`saved_real_estate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`saved_real_estate` ;

CREATE TABLE IF NOT EXISTS `db`.`saved_real_estate` (
  `user_id` INT UNSIGNED NOT NULL,
  `user_real_estate_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_real_estate_id`),
  INDEX `fk_user_has_user_real_estate_user_real_estate1_idx` (`user_real_estate_id` ASC),
  INDEX `fk_user_has_user_real_estate_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_user_real_estate_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_real_estate_user_real_estate1`
    FOREIGN KEY (`user_real_estate_id`)
    REFERENCES `db`.`user_real_estate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`statistic_timestamp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`statistic_timestamp` ;

CREATE TABLE IF NOT EXISTS `db`.`statistic_timestamp` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `statistics_id` INT NOT NULL,
  INDEX `fk_statistic_timestamp_statistics1_idx` (`statistics_id` ASC),
  CONSTRAINT `fk_statistic_timestamp_statistics1`
    FOREIGN KEY (`statistics_id`)
    REFERENCES `db`.`statistics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
